function strng = correct_capitalization(strng)

    idx = regexp([' ' strng],'(?<=\s+)\S','start')-1;
    strng(idx) = upper(strng(idx));

    if strcmp(strng(end),'.')
        strng = strng(1:end-1);
    end
    
    words2check4 = {'A ',... % articles
                    'An',...
                    'The',...
                    'For',... % conjunctions
                    'And',...
                    'Nor',...
                    'But',...
                    'or',...
                    'Yet',...
                    'So',...
                    'At',... % prepositions
                    'Around',...
                    'By',...
                    'After',...
                    'Along',...
                    'For',...
                    'From',...
                    'Of',...
                    'On',...
                    'In',...
                    'To',...
                    'With',...
                    'Without'};
               
    for i = 1:length(words2check4)
        idx = findstr(strng,words2check4{i});
        if (~isempty(idx) && (idx(end) ~= length(strng)-2)) % check if empty or if last word
            if (idx(1) > 1) % check if first word
                strng(idx) = lower(words2check4{i}(1)); % correct all instances
            else
                strng(idx(2:end)) = lower(words2check4{i}(1)); % omit the first word in correction
            end
        end
    end
        
end % correct_case_of_articles()