function [Parameterfile,file_name_PMatlabGP_Controll ] = make_execution_control_file(Compuations_to_do,File_to_execute,Parameterfile_ID,Nice_level)

if nargin==3
    Nice_level=15;
    disp('Nice level is by default 15')
else
    Nice_level =abs(Nice_level);
    if Nice_level>20
       Nice_level=20;
       disp('Nice level has to be bonded by 0 and 20 : 0 = high priority / 20 = low priority');
   end
end
    

Parameterfile                   = ['Parameterfile_for__' File_to_execute '__' Parameterfile_ID];
file_name_PMatlabGP_Controll    = ['execution_control_file__' File_to_execute '__' Parameterfile_ID '.ecf'];
fid                             = fopen(file_name_PMatlabGP_Controll,'w');
fprintf(fid, '------------------------------------------------------------------------------------ \n');
fprintf(fid,['Header of execution_control_file for Executable ' File_to_execute ' and Parameter file ' Parameterfile ' \n']);
fprintf(fid, 'Definition of Computations to be executed is started and closes by 20 times # \n');
fprintf(fid, 'Header has to be ignored \n');
fprintf(fid, 'Definition is structured such \n');
fprintf(fid, '1) Name of file which has to be called - Name can be different for different Process IDs - Function which is called has two arguments (Name_of_parameterfile,ProcessID) \n');
fprintf(fid, '2) Name of the parameter file which is read be the executed file defined in 1) This value has to be used as a function argument of function defined in 1) \n');
fprintf(fid, '3) Process ID - defines the compuation by using detailed info contained in the parameter file - The Process ID has to be used as a function argument of function defined in 1)  \n');
fprintf(fid, '------------------------------------------------------------------------------------ \n');
fprintf(fid, ['This file is automatically generated ' date '                  \n']);
fprintf(fid, ['For further Information contact Gordon Pipa by mail@g-pipa.de or Nan-Hui Chen by nchen@mpih-frankfurt.mpg.de \n']);
fprintf(fid, '------------------------------------------------------------------------------------ \n');
fprintf(fid, '[Nice Level] \n');
fprintf(fid, [num2str(Nice_level) ' \n']);
fprintf(fid, 'Computations to be executed: \n');
fprintf(fid, '#################### \n');
for IDX_Comp=1:length(Compuations_to_do)
    fprintf(fid, [File_to_execute ' ' Parameterfile '.mat ' num2str(Compuations_to_do(IDX_Comp)) ' \n'] );
end
fprintf(fid, '#################### \n');
fprintf(fid,['Nr Calls in total : ' num2str(length(Compuations_to_do)) '  \n']);
fclose(fid);

