function snapshot()

    zipFileName = sprintf('packets_%s.zip', datestr(now, 'yyyymmdd'));

    if (exist(zipFileName, 'file') == 2)
        delete(zipFileName);
    end
    
    if (exist('snapshot.txt', 'file') == 2)
        delete('snapshot.txt');
    end
    
    diary snapshot.txt;
    
%     status = system(['zip ',    zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\_Hippocampome_*"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\AFI_and_Non-hippocampus_related_PMIDs.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\attachment_ephys_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\attachment_ephys_v2.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\attachment_FP_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\attachment_FP_v2.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\attachment_marker_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\attachment_marker_v2.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\attachment_morph_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\attachment_morph_v2.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\attachment_neurite_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\BiomarkerAbbreviations.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\bits_pieces-of-knowledge.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\DG_naming_sources.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\FAQ_for_Data_Mining.doc"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Firing_parameters_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Firing_parameters_v2.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\FP_abbreviations_portal.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\FP_definitions.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\FP_matrix.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Glossary_of_Terms_for_Data_Mining.doc"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\HC-Ephys-v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\HC-Ephys-v2.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_FAQ.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_FAQ.htm"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_FAQ.php"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Feedback_Submissions.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Feedback_Submissions.htm"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Feedback_Submissions.php"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Firing_Pattern_definitions.pptx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Firing_Pattern_definitions.html"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Firing_Pattern_definitions.php"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_FP_Abbreviations.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_FP_Abbreviations.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_FP_Abbreviations.htm"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_FP_Abbreviations.php"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Future_Updates.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Future_Updates.htm"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Future_Updates.php"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_In_Progress.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_In_Progress.htm"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Known_Bug_List.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Known_Bug_List.htm"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Known_Bug_List.php"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Marker_Abbreviations.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Marker_Abbreviations.htm"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Marker_Abbreviations.php"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Ongoing_Literature_Mining.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Ongoing_Literature_Mining.htm"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Ongoing_Literature_Mining.php"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_On-hold_Types.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_On-hold_Types.htm"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_On-hold_Types.php"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Quickstart.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Quickstart.htm"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Quickstart.php"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Supplemental_Evidence.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Supplemental_Evidence.htm"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Supplemental_Evidence.php"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Terms_of_Use.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Terms_of_Use.htm"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Help_Terms_of_Use.php"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Hippocampome_axon-dendrite-soma_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Hippocampome_axon-dendrite-soma_v2.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Hippocampome-Markers_DE-INF_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Hippocampome-Markers_DE-INF_v2.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Instructions_for_Data_Mining_Spread_Sheet.doc"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Interneuron_Supertypes.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Journler_Composition_Book_1.doc"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Journler_Composition_Book_2.doc"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Names_active_classes.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\neurites_quantified_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\packet_notes_v1.1.csv"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\packet_notes_v2.0.csv"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\PoK_PoE.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\portal_ticket_triage_by_date.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\type_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\type_v2.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\URD_ephys_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\URD_ephys_v2.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\URD_FP_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\URD_FP_v2.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\URD_marker_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\URD_marker_v2.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\URD_morph_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\URD_morph_v2.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\URD_neurite_v1.0.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\You_Gantt_Handle_the_Truth.mpp"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\You_Gantt_Handle_the_Truth.xlsx"'])
% 
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Counts\*.pdf"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Counts\*.docx"'])
% 
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Electrophysiological_Digitizations_v2.0\Excel_Digitizing_Template_v8c.xlsm"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Electrophysiological_Digitizations_v2.0\Spikes_for_classification.xlsx"'])
% 
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\eLife_v2.0_Update\eLife_v2.0_Update.docx"'])
% 
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Quantification_of_neurites\Alexander_brainstorming_20170118.pdf"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Quantification_of_neurites\DPL_vs_grid_resolution.pptx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Quantification_of_neurites\How_to_create_a_graded_graph.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Quantification_of_neurites\NMO_34259.pptx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Quantification_of_neurites\NMO-HC.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Quantification_of_neurites\Protocol_for_quantifying_neurites.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Quantification_of_neurites\quantification_notes_*.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Quantification_of_neurites\Quantification_of_Neurites.xlsx"'])
% 
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\Neurite Length estimation\Add info\Ratios.docx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\Neurite Length estimation\Neurons\CA1\*.xlsx"'])    
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\Neurite Length estimation\Neurons\CA2\*.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\Neurite Length estimation\Neurons\CA3\*.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\Neurite Length estimation\Neurons\DG\*.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\Neurite Length estimation\Neurons\EC\*.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\Neurite Length estimation\Neurons\Sub\*.xlsx"'])
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\Neurite Length estimation\Paper\*"'])
% 
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Dropbox\Public\v2.0\v2.0_packets\v2.0_packets_summary.xlsx"'])
%     
%     status = system(['zip -g ', zipFileName, ' "C:\Users\Diek\Box Sync\__Hippocampome_Meeting_Agendas\*.pdf"'])
%     
%     status = system(['zip -gr ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Correlations"'])
%     status = system(['zip -gr ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\Faramarz"'])
%     status = system(['zip -gr ', zipFileName, ' "C:\Users\Diek\Dropbox\20140120-Active_Work\packet notes_v2.0"'])
%     
%     status = system(['zip -gr ', zipFileName, ' "C:\Users\Diek\Dropbox\Public\v2.0\v2.0_packets\round*"'])

    status = system(['zip -r ', zipFileName, ' "C:\Users\Diek\Dropbox\HC database"'])
    
%     status = system(['zip -gr ', zipFileName, ' "C:\Users\Diek\Dropbox\v2.0_figs"'])

    diary off;
    
    status = system(['move ', zipFileName, ' C:\Users\Diek\Dropbox\Hippocampome_Snapshot\', zipFileName])
    
end % snapshot