function cellArray = cell_array_header(nBrainRegions2Save, nCellTypes2Save, nPmids2Save, nDois2Save)

    cellArray{1,1} = 'Hippocampome_ID';
    cellArray{1,2} = 'reason_for_exclusion';
    cellArray{1,3} = 'reason_for_inclusion';
    cellArray{1,4} = 'Supertype_ID';
    cellArray{1,5} = 'neuron_id';
    cellArray{1,6} = 'neuron_name';
    cellArray{1,7} = 'archive';
    cellArray{1,8} = 'note';
    cellArray{1,9} = 'age_classification';
    for i = 1:nBrainRegions2Save
        cellArray{1,i+9} = sprintf('brain_region_%d', i);
    end
    for i = 1:nCellTypes2Save
        cellArray{1,i+9+nBrainRegions2Save} = sprintf('cell_type_%d', i);
    end
    i = 9+nBrainRegions2Save+nCellTypes2Save+1;
    cellArray{1,i} = 'species';
    i = i + 1;
    cellArray{1,i} = 'strain';
    i = i + 1;
    cellArray{1,i} = 'scientific_name';
    i = i + 1;
    cellArray{1,i} = 'stain';
    i = i + 1;
    cellArray{1,i} = 'experiment_condition';
    i = i + 1;
    cellArray{1,i} = 'protocol';
    i = i + 1;
    cellArray{1,i} = 'slicing_direction';
    i = i + 1;
    cellArray{1,i} = 'reconstruction_software';
    i = i + 1;
    cellArray{1,i} = 'objective_type';
    i = i + 1;
    cellArray{1,i} = 'original_format';
    i = i + 1;
    cellArray{1,i} = 'domain';
    i = i + 1;
    cellArray{1,i} = 'attributes';
    i = i + 1;
    cellArray{1,i} = 'magnification';
    i = i + 1;
    cellArray{1,i} = 'upload_date';
    i = i + 1;
    cellArray{1,i} = 'deposition_date';
    i = i + 1;
    cellArray{1,i} = 'shrinkage_reported';
    i = i + 1;
    cellArray{1,i} = 'shrinkage_corrected';
    i = i + 1;
    cellArray{1,i} = 'reported_value';
    i = i + 1;
    cellArray{1,i} = 'reported_xy';
    i = i + 1;
    cellArray{1,i} = 'reported_z';
    i = i + 1;
    cellArray{1,i} = 'corrected_value';
    i = i + 1;
    cellArray{1,i} = 'corrected_xy';
    i = i + 1;
    cellArray{1,i} = 'corrected_z';
    i = i + 1;
    cellArray{1,i} = 'soma_surface';
    i = i + 1;
    cellArray{1,i} = 'surface';
    i = i + 1;
    cellArray{1,i} = 'volume';
    i = i + 1;
    cellArray{1,i} = 'slicing_thickness';
    i = i + 1;
    cellArray{1,i} = 'min_age';
    i = i + 1;
    cellArray{1,i} = 'max_age';
    i = i + 1;
    cellArray{1,i} = 'min_weight';
    i = i + 1;
    cellArray{1,i} = 'max_weight';
    i = i + 1;
    cellArray{1,i} = 'png_url';
    for j = 1:nPmids2Save
        cellArray{1,j+i} = sprintf('reference_pmid_%d', j);
    end
    for j = 1:nDois2Save
        cellArray{1,j+i+nPmids2Save} = sprintf('reference_doi_%d', j);
    end
    i = i+nPmids2Save+nDois2Save+1;
    cellArray{1,i} = 'physical_Integrity';
    i = i + 1;
    cellArray{1,i} = 'x0x5F_links';
    
end % cell_array_header()
    
